import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/components/header'
import { AuthProvider } from '@/components/provider/auth-provider'
import { Toaster } from '@/components/ui/toaster'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body>
        <AuthProvider>
          <Header />
          <main className="pb-8 pt-4">{children}</main>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  )
}
